name: hmmer_compare
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python~=3.10
  - pip
  - setuptools>=60.7
  - pytest~=7.0.1
  - pytest-datadir~=1.3.1
  - pyhmmer~=0.7.2
  - numpy
  - scipy
  - numba~=0.56.4
  - pip:
    - -e .
