name: hmmer_compare
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python~=3.9
  - pip
  - setuptools>=60.7
  - pytest~=7.0.1
  - pytest-datadir~=1.3.1
  - pyhmmer~=0.6.0
  - numpy
  - scipy
  - pip:
    - -e .
